// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Grid$ReactTemplate = require("./Grid.bs.js");

var component = ReasonReact.reducerComponent("Game");

var initialState = /* record */[
  /* grid : :: */[
    /* :: */[
      /* Dead */0,
      /* :: */[
        /* Dead */0,
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* :: */[
      /* :: */[
        /* Dead */0,
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ],
      /* :: */[
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ],
        /* :: */[
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Alive */1,
                  /* :: */[
                    /* Alive */1,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Alive */1,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ],
            /* :: */[
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ],
              /* :: */[
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* :: */[
                                    /* Dead */0,
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ],
                /* :: */[
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* :: */[
                                    /* Dead */0,
                                    /* :: */[
                                      /* Dead */0,
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ],
                  /* :: */[
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* :: */[
                                    /* Dead */0,
                                    /* :: */[
                                      /* Dead */0,
                                      /* :: */[
                                        /* Dead */0,
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ],
                    /* :: */[
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* :: */[
                                    /* Dead */0,
                                    /* :: */[
                                      /* Dead */0,
                                      /* :: */[
                                        /* Dead */0,
                                        /* :: */[
                                          /* Dead */0,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ],
  /* gameState : Paused */1
];

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("div", {
                          className: "game"
                        }, ReasonReact.element(/* None */0, /* None */0, Grid$ReactTemplate.make(param[/* state */1][/* grid */0], /* array */[])));
            }),
          /* initialState */(function () {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              return /* Update */Block.__(0, [initialState]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.initialState = initialState;
exports.make = make;
/* component Not a pure module */
