// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Grid$ReactTemplate = require("./Grid.bs.js");
var Utils$ReactTemplate = require("./Utils.bs.js");

var initialState_000 = /* grid : :: */[
  /* :: */[
    /* Dead */0,
    /* :: */[
      /* Dead */0,
      /* :: */[
        /* Dead */0,
        /* :: */[
          /* Alive */1,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ],
  /* :: */[
    /* :: */[
      /* Dead */0,
      /* :: */[
        /* Dead */0,
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Alive */1,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* :: */[
      /* :: */[
        /* Dead */0,
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Alive */1,
            /* :: */[
              /* Alive */1,
              /* :: */[
                /* Alive */1,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ],
      /* :: */[
        /* :: */[
          /* Dead */0,
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ],
        /* :: */[
          /* :: */[
            /* Dead */0,
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              /* Dead */0,
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Alive */1,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ],
            /* :: */[
              /* :: */[
                /* Dead */0,
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Alive */1,
                                /* :: */[
                                  /* Dead */0,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ],
              /* :: */[
                /* :: */[
                  /* Dead */0,
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Alive */1,
                              /* :: */[
                                /* Alive */1,
                                /* :: */[
                                  /* Alive */1,
                                  /* :: */[
                                    /* Dead */0,
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ],
                /* :: */[
                  /* :: */[
                    /* Dead */0,
                    /* :: */[
                      /* Dead */0,
                      /* :: */[
                        /* Dead */0,
                        /* :: */[
                          /* Dead */0,
                          /* :: */[
                            /* Dead */0,
                            /* :: */[
                              /* Dead */0,
                              /* :: */[
                                /* Dead */0,
                                /* :: */[
                                  /* Dead */0,
                                  /* :: */[
                                    /* Dead */0,
                                    /* :: */[
                                      /* Dead */0,
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var initialState_002 = /* intervalId : record */[/* contents */undefined];

var initialState = /* record */[
  initialState_000,
  /* gameState : Playing */0,
  initialState_002
];

function toggleField(rowI, colI, grid) {
  return List.mapi((function (rowIndex, row) {
                return List.mapi((function (colIndex, value) {
                              var match = colI === colIndex && rowI === rowIndex;
                              if (match) {
                                if (value) {
                                  return /* Dead */0;
                                } else {
                                  return /* Alive */1;
                                }
                              } else {
                                return value;
                              }
                            }), row);
              }), grid);
}

function clearGrid(grid) {
  return List.map((function (row) {
                return List.map((function () {
                              return /* Dead */0;
                            }), row);
              }), grid);
}

var component = ReasonReact.reducerComponent("Game");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var match = state[/* gameState */1];
              if (match) {
                return /* () */0;
              } else {
                state[/* intervalId */2][0] = Js_primitive.some(setInterval((function () {
                            return Curry._1(send, /* NextFrame */0);
                          }), 200));
                return /* () */0;
              }
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var match = state[/* gameState */1] === /* Playing */0;
              return React.createElement("div", {
                          className: "game"
                        }, ReasonReact.element(undefined, undefined, Grid$ReactTemplate.make(state[/* grid */0], (function (row, col) {
                                    return Curry._1(send, /* ToggleField */[
                                                row,
                                                col
                                              ]);
                                  }), /* array */[])), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(send, /* TogglePlay */1);
                                })
                            }, Utils$ReactTemplate.toString(match ? "Pause" : "Play")), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(send, /* Clear */2);
                                })
                            }, Utils$ReactTemplate.toString("Reset")));
            }),
          /* initialState */(function () {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                switch (action) {
                  case 0 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* grid */Utils$ReactTemplate.calcNextState(state[/* grid */0]),
                                  /* gameState */state[/* gameState */1],
                                  /* intervalId */state[/* intervalId */2]
                                ]]);
                  case 1 : 
                      var match = state[/* gameState */1];
                      if (match) {
                        return /* UpdateWithSideEffects */Block.__(2, [
                                  /* record */[
                                    /* grid */state[/* grid */0],
                                    /* gameState : Playing */0,
                                    /* intervalId */state[/* intervalId */2]
                                  ],
                                  (function (self) {
                                      state[/* intervalId */2][0] = Js_primitive.some(setInterval((function () {
                                                  return Curry._1(self[/* send */3], /* NextFrame */0);
                                                }), 200));
                                      return /* () */0;
                                    })
                                ]);
                      } else {
                        var match$1 = state[/* intervalId */2][0];
                        if (match$1 !== undefined) {
                          var id = Js_primitive.valFromOption(match$1);
                          return /* UpdateWithSideEffects */Block.__(2, [
                                    /* record */[
                                      /* grid */state[/* grid */0],
                                      /* gameState : Paused */1,
                                      /* intervalId */state[/* intervalId */2]
                                    ],
                                    (function () {
                                        clearInterval(id);
                                        return /* () */0;
                                      })
                                  ]);
                        } else {
                          return /* Update */Block.__(0, [initialState]);
                        }
                      }
                  case 2 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* grid */clearGrid(state[/* grid */0]),
                                  /* gameState */state[/* gameState */1],
                                  /* intervalId */state[/* intervalId */2]
                                ]]);
                  
                }
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* grid */toggleField(action[0], action[1], state[/* grid */0]),
                            /* gameState */state[/* gameState */1],
                            /* intervalId */state[/* intervalId */2]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var speed = 200;

exports.initialState = initialState;
exports.speed = speed;
exports.toggleField = toggleField;
exports.clearGrid = clearGrid;
exports.component = component;
exports.make = make;
/* component Not a pure module */
